export const ADD_MOVIE = "ADD_MOVIE";
export const FILTER_MOVIE_WATCH_LIST = "FILTER_MOVIE_WATCH_LIST";
export const FILTER_MOVIE_WATCHED_LIST = "FILTER_MOVIE_WATCHED_LIST";
export const CHANGE_WHATCHED = "CHANGE_WHATCHED";
export const DELETE_MOVIE= "DELETE_MOVIE";